version: "2"

services:

  main:
    restart: always
    build:
      context: ./praiseme
    stdin_open: true
    tty: true
    volumes:
      - ./praiseme:/usr/src/app/
    environment:
      - DISCORD_PRAISEME_TOKEN=${DISCORD_PRAISEME_TOKEN}
